const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {PNG}=require(process.env.PNGJS_MODULE||'pngjs');
const {browserTask,bands}=require('./browser-harness.cjs');
const output=process.env.CFP_QA_OUTPUT;if(!output)throw Error('CFP_QA_OUTPUT must name a task-owned directory');fs.mkdirSync(output,{recursive:true});
const report={scope:'Production content and trusted compositor dispatcher, source evaluation, CDP screenshots in synthetic profile; no extension installation/native captureVisibleTab/downloads.',bands:[]};
browserTask(()=>bands(20),async({page,base,source,browser})=>{
 report.browser=browser;
 async function compose(id){const p=await page.evaluate(()=>qa.prepare());let previous=null,count=0;const plan=await page.evaluate(p=>__cfpProtocol.makeTraversal(p),p);
  async function request(type,payload={}){return page.evaluate(m=>__cfpCompositorHandle(m),{target:'cfp-offscreen',protocolVersion:1,requestId:require('node:crypto').randomUUID(),operationId:p.operationId,sessionId:p.sessionId,owner:p.owner,type,...payload});}
  const start=await request('start',{prep:p});assert.equal(start.ok,true,JSON.stringify(start));
  while(true){const spec=await page.evaluate(({plan,previous})=>__cfpProtocol.nextFrameSpec(plan,previous),{plan,previous});if(!spec)break;await page.evaluate(spec=>qa.moveTo(qa.getState(),spec),spec);const preSnapshot=await page.evaluate(spec=>qa.snapshot(qa.getState(),spec),spec);const screenshot=await page.screenshot({timeout:10000});const postSnapshot=await page.evaluate(spec=>qa.snapshot(qa.getState(),spec),spec);const r=await request('frame',{spec,preSnapshot,postSnapshot,dataUrl:'data:image/png;base64,'+screenshot.toString('base64')});assert.equal(r.ok,true,JSON.stringify(r));await page.evaluate(({spec,r})=>qa.acceptFrame(qa.getState(),{spec,bitmapWidth:r.bitmapWidth,bitmapHeight:r.bitmapHeight,rect:r.rect,novelRect:r.novelRect}),{spec,r});previous=spec;assert.ok(++count<200);}
  const restored=await page.evaluate(()=>qa.restore());assert.equal(restored.status,"acknowledged");const intentId=require('node:crypto').randomUUID(),finished=await request('finish',{intentId});assert.equal(finished.ok,true,JSON.stringify(finished));const bytes=Buffer.from(await page.evaluate(async url=>Array.from(new Uint8Array(await(await fetch(url)).arrayBuffer())),finished.url));assert.equal((await request('revoke',{url:finished.url,intentId})).ok,true);fs.writeFileSync(path.join(output,id+'.png'),bytes);return PNG.sync.read(bytes);
 }
 for(const height of [100,180,190,191]){await page.setViewportSize({width:400,height});await page.goto(base+'/bands');await page.evaluate(source);await page.evaluate(()=>scrollTo(0,37));const png=await compose('bands-'+height);assert.equal(png.height,1000);assert.equal(await page.evaluate(()=>scrollY),37);for(let y=0;y<1000;y++){const i=Math.floor(y/50),o=(y*png.width+300)*4;assert.deepEqual([...png.data.subarray(o,o+3)],[20+i*5,40+i*3,80+i*2],`viewport ${height} row ${y}`);}report.bands.push({height,width:png.width,outputHeight:png.height,allRowsVerified:true});console.log('PIXELS PASS',height);if(height===180){const repeated=await compose('bands-repeat');assert.deepEqual(repeated.data,png.data);report.repeatedCapture=true;}}
 fs.writeFileSync(path.join(output,'chrome-pixel-report.json'),JSON.stringify(report,null,2));
}).catch(e=>{console.error(e);process.exitCode=1;});
