'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawnSync}=require('node:child_process');
const root=path.resolve(__dirname,'..');
const workflow=fs.readFileSync(path.join(root,'.github/workflows/publish-stores.yml'),'utf8');
// Restricted source inspector for this workflow's existing two-space jobs and
// six-space steps. This is not a GitHub Actions emulator or general YAML parser.
function job(name,source=workflow){const match=source.match(new RegExp('^  '+name+':\\r?\\n([\\s\\S]*?)(?=^  [a-z][a-z-]*:|$(?![\\s\\S]))','m'));assert.ok(match,'Missing job '+name);return match[1];}
function steps(body){return body.split(/^      - name: /m).slice(1).map(block=>{const name=block.slice(0,block.indexOf('\n')).trim();const run=block.match(/^        run: (.*)$/m);if(!run)return {name,block};return {name,block,command:run[1]==='|'?block.split('\n').filter(line=>line.startsWith('          ')).map(line=>line.slice(10)).join('\n').trim():run[1].trim()};});}
function gates(source=workflow){const build=job('build',source),list=steps(build);const locate=name=>{const index=list.findIndex(s=>s.name===name);assert.ok(index>=0,'Missing build step: '+name);return index;};const syntax=locate('Check JavaScript syntax'),shell=locate('Check publisher shell syntax'),regressions=locate('Run capture reliability regressions'),packages=locate('Build Chrome and Firefox packages');assert.ok(syntax<shell && shell<regressions && regressions<packages,'Checks must precede packaging');assert.equal(list[shell].command,'bash -n scripts/publish_chrome.sh');assert.equal(list[regressions].command,'node --test tests/*.test.cjs');assert.equal(list[packages].command,'python scripts/build.py');assert.doesNotMatch(build,/continue-on-error:|\b(?:always|failure|cancelled)\s*\(/);for(const name of ['github-release','publish-firefox','publish-chrome']){const body=job(name,source);assert.match(body,/^    needs: build\s*$/m,name+' must depend on the tested build');assert.doesNotMatch(body,/\b(?:always|failure|cancelled)\s*\(/,name+' must preserve success gating');}return list.slice(syntax,packages+1).filter(step=>step.command).map(step=>step.command).join('\n');}
function bash(){if(process.env.CFP_BASH_EXECUTABLE)return process.env.CFP_BASH_EXECUTABLE;if(process.platform==='win32')return path.join(process.env.ProgramFiles||'C:\\Program Files','Git','bin','bash.exe');return 'bash';}
function cleanEnvironment(tmp){const env={PATH:process.env.PATH,CFP_NODE:process.execPath,TMP:tmp,TEMP:tmp,TMPDIR:tmp,HOME:tmp};for(const key of ['SystemRoot','WINDIR','COMSPEC'])if(process.env[key])env[key]=process.env[key];return env;}
function failureFixture(command,{badShell=false,passingRegression=false}={}){const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'cfp-p7-gate-'));try{fs.mkdirSync(path.join(tmp,'tests'));fs.mkdirSync(path.join(tmp,'scripts'));for(const name of ['capture-protocol.js','content.js','service-worker.js','offscreen.js','popup.js'])fs.writeFileSync(path.join(tmp,name),'"use strict";\n');fs.writeFileSync(path.join(tmp,'scripts/publish_chrome.sh'),badShell?'#!/usr/bin/env bash\nif then\n':'#!/usr/bin/env bash\nset -euo pipefail\n');fs.writeFileSync(path.join(tmp,'tests/gate.test.cjs'),passingRegression?'const {test}=require("node:test");test("synthetic pass",()=>{});':fs.readFileSync(path.join(__dirname,'fixtures/publisher-failing-regression.cjs')));
 const script='set -euo pipefail\nnode(){ "$CFP_NODE" "$@"; }\npython(){ printf "packaging\\n" >> calls.log; }\ngh(){ printf "privileged-gh\\n" >> calls.log; }\ncurl(){ printf "privileged-curl\\n" >> calls.log; }\nweb_ext(){ printf "privileged-firefox\\n" >> calls.log; }\n'+command+'\ngh release create synthetic\ncurl synthetic\nweb_ext sign synthetic\n';fs.writeFileSync(path.join(tmp,'gate.sh'),script);const result=spawnSync(bash(),['--noprofile','--norc','-e','gate.sh'],{cwd:tmp,env:cleanEnvironment(tmp),encoding:'utf8',timeout:20000});if(result.error)throw result.error;assert.notEqual(result.signal,'SIGTERM','Fixture must finish within bound');return {status:result.status,output:result.stdout+result.stderr,calls:fs.existsSync(path.join(tmp,'calls.log'))?fs.readFileSync(path.join(tmp,'calls.log'),'utf8').trim().split('\n'):[]};
 }finally{const resolved=path.resolve(tmp);assert.ok(resolved.startsWith(path.resolve(os.tmpdir())+path.sep+'cfp-p7-gate-'));fs.rmSync(resolved,{recursive:true,force:true});}}
test('publisher build runs dependency-free regressions and shell syntax before packaging',()=>{gates();});
test('syntax-valid failing regression stops packaging and every publisher dependency',()=>{const result=failureFixture(gates());assert.notEqual(result.status,0);assert.match(result.output,/publisher gate rejects a failing regression/);assert.match(result.output,/ERR_ASSERTION/);assert.deepEqual(result.calls,[]);});
test('invalid publisher shell stops packaging and privileged process fakes',()=>{const result=failureFixture(gates(),{badShell:true,passingRegression:true});assert.notEqual(result.status,0);assert.match(result.output,/syntax error/);assert.deepEqual(result.calls,[]);});
test('passing fixture proves packaging and privileged recording fakes are reachable',()=>{const result=failureFixture(gates(),{passingRegression:true});assert.equal(result.status,0,result.output);assert.deepEqual(result.calls,['packaging','privileged-gh','privileged-curl','privileged-firefox']);});
test('publisher gate fixture catches missing regression and failure-bypassing dependency mutations',()=>{assert.throws(()=>gates(workflow.replace('        run: node --test tests/*.test.cjs','        run: node --check content.js')));for(const name of ['github-release','publish-firefox','publish-chrome']){const original=job(name),mutated=workflow.replace(original,original.replace('needs: build','needs: unrelated'));assert.throws(()=>gates(mutated),/must depend/);}assert.throws(()=>gates(workflow.replace('    needs: build','    needs: build\n    if: always()')),/success gating/);});
